### ISSUE TITLE
Compilation Error R 4.0.0

### ISSUE THREAD

**Issue by DillonHammill** [RGLab/RProtoBufLib#12]
Hi @mikejiang & @jacobpwagner,

I pulled down the latest `protobuf` binaries, extracted to C:/ and set environment variable as always. When I try to install `RProtoBufLib` I get compilation errors:

```{r}
> devtools::install_github("RGLab/RProtoBufLib")
Downloading GitHub repo RGLab/RProtoBufLib@master
√  checking for file 'C:\Users\localuseradmin.JCSMR-028197PL\AppData\Local\Temp\Rtmpg5uvjO\remotes3d4c572542b\RGLab-RProtoBufLib-d7d10f8/DESCRIPTION' (683ms)
-  preparing 'RProtoBufLib':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  running 'cleanup.win'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'RProtoBufLib_2.1.0.tar.gz'
   Warning: file 'RProtoBufLib/cleanup' did not have execute permissions: corrected
   Warning: file 'RProtoBufLib/configure' did not have execute permissions: corrected
   
* installing *source* package 'RProtoBufLib' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
mkdir -p "C:/Program Files/R/R-4.0.0/library/00LOCK-RProtoBufLib/00new/RProtoBufLib/include"
cp -r C:/protobuf/include/google "C:/Program Files/R/R-4.0.0/library/00LOCK-RProtoBufLib/00new/RProtoBufLib/include"
mkdir -p "C:/Program Files/R/R-4.0.0/library/00LOCK-RProtoBufLib/00new/RProtoBufLib/lib/i386"
cp  C:/protobuf/lib/i386/libprotobuf-lite.a "C:/Program Files/R/R-4.0.0/library/00LOCK-RProtoBufLib/00new/RProtoBufLib/lib/i386/libprotobuf-lite.a"
"C:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG          -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c dummy.cpp -o dummy.o
C:/rtools40/mingw32/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o RProtoBufLib.dll tmp.def dummy.o -LC:/PROGRA~1/R/R-40~1.0/bin/i386 -lR
: symbol not definedbin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot export _Z19dummy_RProtobuf_funv
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'RProtoBufLib'
* removing 'C:/Program Files/R/R-4.0.0/library/RProtoBufLib'
* restoring previous 'C:/Program Files/R/R-4.0.0/library/RProtoBufLib'
Error: Failed to install 'RProtoBufLib' from GitHub:
  (converted from warning) installation of package ‘C:/Users/LOCALU~1.JCS/AppData/Local/Temp/Rtmpg5uvjO/file3d4c4195424d/RProtoBufLib_2.1.0.tar.gz’ had non-zero exit status
```

**Comment by jacobpwagner** [comment]
Hmm. A couple of ideas, as this is likely related in some way to the big Rtools 4.0 changeover. Have you updated the Windows protobuf binary to the version built with Rtools 4.0?. That is, you probably followed these instructions before:
https://github.com/RGLab/RProtoBufLib/blob/d7d10f8c9cfec67ffd8597c8b1d448246fb12515/INSTALL#L4-L8
But have you done that since you upgraded to R 4.0, because there's a new binary:
http://rglab.github.io/binaries/

Try deleting the old `C:\protobuf` and replacing it, making sure the environment variable is set, and then re-trying `devtools::install_github("RGLab/RProtoBufLib")`.

If that fails, can you give me your full output of `.libPaths()`? I suppose it could be a permissions issue. For my Windows 10 installation, if I try to force installation to the base R library path you are pointing at, I run in to permissions issues.

**Comment by DillonHammill** [comment]
@jacobpwagner, yes I got the latest binaries, replaced the old one and restarted. I am away from my computer now but I will send this through for you to look at tomorrow.

**Comment by mikejiang** [comment]
Again, windows binary is available from bioc (and it builds ok on their server) http://bioconductor.org/packages/3.12/bioc/html/RProtoBufLib.html

RProtoBufLib is rarely updated (maybe once every 3 years) and so it is safe for you to pull the prebuilt package from bioc instead of chasing bugs in the dicey windows gnu build machinery.

**Comment by DillonHammill** [comment]
Thanks @mikejiang, I decided to take the easy route as I could not get this to work. I always have my R located in Program Files @jacobpwagner and I am running R with admin rights:
```{r}
.libPaths()
[1] "C:/Program Files/R/R-4.0.0/library"
```
I noticed that the compilation issues are not restricted to RProtoBufLib, there are a number of other packages that would not compile properly. Maybe this is to do with the change to Rtools 4.0?

**Comment by jacobpwagner** [comment]
Yeah, I was going to ask you to just install a couple non-RGLab packages from source to test how your Rtools 4.0 setup was working, but it appears that the answer to that question is "not great". I'm not sure why though, as it's all working smoothly for me under Windows 10. Mike is right, `RProtoBufLib` is very rarely updated so the binary from Bioconductor is a good choice. And yeah, if you're running as admin then you should probably have no permissions issues for that library directory. That was kind of a long shot thought anyway.

**Comment by DillonHammill** [comment]
Strangely flowWorkspace compiles successfully but has a huge printout.

**Comment by DillonHammill** [comment]
I might try updating my Rtools again in case there is a patch that I am missing.

**Comment by DillonHammill** [comment]
I think we can close this now, I can confirm all RGLab packages are now compiling with the latest [rtools](https://cran.r-project.org/bin/windows/Rtools/) on windows. There were some patches added for R 4.0.2 which has fixed my compilation problems - users running R 4.0.0 may need to update their Rtools if things are not compiling properly.
